# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(pipeline-level-variable)
  - job: SecondJob
    steps:
    - bash: echo SecondJob
- stage: DevDeploy
  variables:
   environment: dev
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    -   bash: echo $(envrionment)DevDeploy
- stage: QADeploy
  variables:
   environment: dev
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps:
    -   bash: echo $(environment)QADeploy
- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployJob
    steps:
    -   bash: echo DevDeployJob


